---
- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    shell: "{{ user_shell }}"
    groups: "{{ user_groups | join(',') }}"
    home: "{{ user_home }}"
    create_home: yes
    state: present
    password: "{{ user_password | default(omit) }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'
  when: user_ssh_key != ""

- name: Add authorized SSH key (if provided)
  ansible.builtin.copy:
    dest: "{{ user_home }}/.ssh/authorized_keys"
    content: "{{ user_ssh_key }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
  when: user_ssh_key != ""
