all:
  hosts: {}

  children:
    local:
      children:
        control_plane:
          hosts:
            localhost:

    hosting:
      children:
        proxmox:
          hosts:
            pve01.fouchger.uk:

    remote:
      children:
        # monitoring:
        #   hosts:
        #     prom01.fouchger.uk:
        #     graf01.fouchger.uk:

        network:
          children:
            dhcp:
              hosts:
                dhcp01.fouchger.uk:

            dns:
              hosts:
                dns01.fouchger.uk:

        #     ad:
        #       hosts:
        #         ad.fouchger.uk:

        #     adblock:
        #       hosts:
        #         adblock01.fouchger.uk:
        #         pihole01.fouchger.uk: