---
- name: Copy controller SSH key to each host via ssh-copy-id
  hosts: remote
  gather_facts: false
  vars:
    ssh_user: root
    ssh_key_path: "$HOME/.ssh/id_ed25519.pub"
  roles:
    - role: ansible-ssh-copy-id
