# homelab2/ansible/roles/ssh_authorized_keys/tasks/main.yml
---
# 1) Ensure a keypair exists on the CONTROLLER (delegated)
- name: Generate an OpenSSH keypair on the controller if missing
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: "{{ ssh_key_type }}"
    regenerate: full_idempotence
    private_key_format: auto
  delegate_to: localhost
  run_once: true

# 2) Read the public key from the CONTROLLER
- name: Read controller public key
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  ansible.builtin.slurp:
    src: "{{ ssh_key_path }}.pub"
  delegate_to: localhost
  register: controller_pubkey_b64
  run_once: true

# 3) Add the controller public key into the target user's authorized_keys
- name: Authorize controller key on targets for user {{ ssh_user }}
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ controller_pubkey_b64.content | b64decode }}"
    manage_dir: true
  become: true
